config/routes.rb
Baazino::Application.routes.draw do

  resources :images

  resources :videos

  resources :profiles

  resources :likes

  resources :game_rates

  resources :platforms

  resources :banks

  resources :developer_accounts

  resources :developers

  resources :reviews

  resources :gates

  resources :genres

  resources :comments

  resources :purchases

  devise_for :users, :controllers => {:registrations => "registrations"}

  mount Ckeditor::Engine => "/ckeditor"

  resources :games do
    member do
      put "like", to: "games#upvote"
      put "dislike", to: "games#downvote"
      get "download"
    end
  end

   root 'games#index'

     get 'purchased_games' => 'purchases#purchased_games'

     get 'topgames' => 'games#all_top'
     get 'newgames' => 'games#all_new'
     get 'dowloadedgames' => 'games#all_downloaded'
     get 'genres_menu' => 'games#genres_menu'

  resources :game do
    resources :comments
  end
end

app/models/bank.rb
class Bank < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  belongs_to :developer_account
  belongs_to :user
  has_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :developer
  belongs_to :review
  belongs_to :genre
  belongs_to :platform
  has_one :game_rate
  has_one :video
  accepts_nested_attributes_for :review
  accepts_nested_attributes_for :video

  acts_as_votable
  acts_as_commentable

  has_attached_file :install_file
  do_not_validate_attachment_file_type :install_file

  has_attached_file :cover_photo
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    where("game_name like ? or description like ?", "%#{query}%", "%#{query}%")
  end
end

app/models/game_rate.rb
class GameRate < ActiveRecord::Base
  belongs_to :game
end

app/models/gate.rb
class Gate < ActiveRecord::Base
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :games
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :game
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/platform.rb
class Platform < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :default_url => "empty_avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  belongs_to :gate
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :developer
  has_many :purchases
  has_one :profile
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :game

  has_attached_file :video_file
  do_not_validate_attachment_file_type :video_file
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @game = Game.find params[:game_id]
    @comment = @game.comments.new(params[:comment].permit(:body))
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @game
  end

  

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
      @comment = Comment.find(params[:id])
      if @comment.destroy
        render :json => @comment, :status => :ok
      else
        render :js => "alert('error deleting comment');"
      end
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:stars, :text, :submit_date, :user_id, :game_id)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def all_rates
    Game.joins(:game_rate).order("game_rates.total desc")
  end

  def all_downloads
    Game.joins(:game_info).order("game_infos.downloads_num desc")
  end

  def all_new
    Game.order(:created_at => :desc)
  end

  def top_rates
    Game.joins(:game_rate).order("game_rates.total desc").limit(5)
  end

  def most_downloads
    Game.order(:downloads_num => :desc).limit(5)
  end

  def new_ones
    Game.order(:created_at => :desc).limit(5)
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
<hr/>
 <%= link_to "×", comment_path(comment), :method => :delete, :remote => true, :confirm => "Are you sure you want to remove this comment?", :disable_with => "×", :class => 'close' %>
 <h4>
  <%= comment.user.username %>
  <small>
  <%= comment.updated_at %>
  </small>
</h4>
<p>
<%= comment.body %>
</p>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= simple_form_for comment, :remote => true do |f| %>
    <%= f.input :body, :input_html => { :rows => "2" }, :label => false %>
    <%= f.input :commentable_id, :as => :hidden, :value => comment.commentable_id %>
    <%= f.input :commentable_type, :as => :hidden, :value => comment.commentable_type %>
    <%= f.button :submit, :class => "btn btn-primary", :disable_with => "Submitting…" %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Stars</th>
      <th>Text</th>
      <th>Submit date</th>
      <th>User</th>
      <th>Game</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.stars %></td>
        <td><%= comment.text %></td>
        <td><%= comment.submit_date %></td>
        <td><%= comment.user %></td>
        <td><%= comment.game %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stars:</strong>
  <%= @comment.stars %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Submit date:</strong>
  <%= @comment.submit_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Game:</strong>
  <%= @comment.game %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>