config/routes.rb
Baazino::Application.routes.draw do

  resources :images

  resources :videos

  resources :profiles

  resources :likes

  resources :game_rates

  resources :platforms

  resources :banks

  resources :developer_accounts

  resources :developers

  resources :reviews

  resources :gates

  resources :genres

  resources :comments

  resources :purchases

  devise_for :users, :controllers => {:registrations => "registrations"}

  mount Ckeditor::Engine => "/ckeditor"

  resources :games do
    member do
      put "like", to: "games#upvote"
      put "dislike", to: "games#downvote"
      get "download"
    end
  end

   root 'games#index'

     get 'purchased_games' => 'purchases#purchased_games'

     get 'topgames' => 'games#all_top'
     get 'newgames' => 'games#all_new'
     get 'dowloadedgames' => 'games#all_downloaded'
     get 'genres_menu' => 'games#genres_menu'

  resources :game do
    resources :comments
  end
end

app/models/bank.rb
class Bank < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  belongs_to :developer_account
  belongs_to :user
  has_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :developer
  belongs_to :review
  belongs_to :genre
  belongs_to :platform
  has_one :game_rate
  has_one :video
  accepts_nested_attributes_for :review
  accepts_nested_attributes_for :video

  acts_as_votable
  acts_as_commentable

  has_attached_file :install_file
  do_not_validate_attachment_file_type :install_file

  has_attached_file :cover_photo
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    where("game_name like ? or description like ?", "%#{query}%", "%#{query}%")
  end
end

app/models/game_rate.rb
class GameRate < ActiveRecord::Base
  belongs_to :game
end

app/models/gate.rb
class Gate < ActiveRecord::Base
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :games
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :game
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/platform.rb
class Platform < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :default_url => "empty_avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  belongs_to :gate
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :developer
  has_many :purchases
  has_one :profile
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :game

  has_attached_file :video_file
  do_not_validate_attachment_file_type :video_file
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:download]

  def genres_menu
    Genre.all
    respond_to do |format|
      format.js
    end
   end

  def download
    @game = Game.find(params[:id])

    if(!Purchase.where(game_id: @game.id, user_id: current_user.id).first)
      Purchase.create(:game => @game, :price=> @game.price, :user=> current_user)
      if(!@game.downloads_num)
        @game.downloads_num = 0
      end
      @game.downloads_num += 1
      @game.update(:downloads_num => @game.downloads_num)
    end

    redirect_to @game.install_file.url
  end

  def upvote
      @game = Game.find(params[:id])
      @game.liked_by current_user
      redirect_to @game
  end

  def downvote
    @game = Game.find(params[:id])
    @game.downvote_from current_user
    redirect_to @game
  end

  def all_downloaded

  end
  # GET /games
  # GET /games.json
  def index
    if params[:search]
      @games = Game.search(params[:search]).order("created_at DESC")
      @isFirstPage = false
    elsif params[:genre_id]
      @games = Genre.find(params[:genre_id]).games
      @isFirstPage = false
    else
      @games = Game.all
      @isFirstPage = true
    end

  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find params[:id]
    @comment = Comment.new
  end

  # GET /games/new
  def new
    @game = Game.new
    @game.build_video
    @game.build_review
  end

  # GET /games/1/edit
  def edit
      if !user_signed_in?
        redirect_to action: :index
      end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.developer = current_user.developer

    respond_to do |format|
      if @game.save
        GameRate.create(:game_id => @game.id)

        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      #params.require(:game).permit(:game_name, :version, :create_date, :release_date, :description, :developer_id, :genre_id, :review_id, :price, :install_file, :platform_id, :support_version, :cover_photo, :downloads_num, :review_attributes, :video_attributes)
      params.require(:game).permit!
    end


end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def all_rates
    Game.joins(:game_rate).order("game_rates.total desc")
  end

  def all_downloads
    Game.joins(:game_info).order("game_infos.downloads_num desc")
  end

  def all_new
    Game.order(:created_at => :desc)
  end

  def top_rates
    Game.joins(:game_rate).order("game_rates.total desc").limit(5)
  end

  def most_downloads
    Game.order(:downloads_num => :desc).limit(5)
  end

  def new_ones
    Game.order(:created_at => :desc).limit(5)
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
<% if @game.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

	<ul>
		<% @game.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :game_name %>
	<br>
	<%= f.text_field :game_name %>
</div>
<div class="field">
	<%= f.label :version %>
	<br>
	<%= f.text_field :version %>
</div>
<div class="field">
	<%= f.label :description %>
	<br>
	<%= f.text_field :description %>
</div>
<div class="field">
	<%= f.label :developer_id %>
	<br>
	<%= f.text_field :developer_id %>
</div>
<div class="field">
	<%= f.label :review_id %>
	<br>
	<%= f.text_field :review_id %>
</div>
<div class="field">
	<%= f.label :price %>
	<br>
	<%= f.text_field :price %>
</div>

<%= f.file_field :install_file %>

<%= f.file_field :cover_photo %>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/games/all_downloaded.html.erb
<div class="container">
	<div class="title">
		<h2>بیشترین دانلود</h2>
	</div>
	<% all_new.each do |game| %>
	<%= link_to game, :class => "appLink" do %>
	<article class="app">
		<div class= "coverPhoto">
			<% if game.cover_photo %>
			<%= image_tag game.cover_photo.url %>
			<% end%>
		</div>
		<div class="gameName">
			<%= game.game_name %>
		</div>
		<div class="cat">
			<%= game.description %>
		</div>
		<div class="priceMain">
			<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
		</div>
	</article>
	<% end %>
	<% end %>
</div>

app/views/games/all_new.html.erb
<div class="container">
	<div class="title">
		<h2>تازه ها</h2>
	</div>
	<% all_new.each do |game| %>

		<%= link_to game, :class => "appLink" do %>
			<article class="app">
				<div class= "coverPhoto">
					<% if game.cover_photo %>
						<%= image_tag game.cover_photo.url %>
					<% end%>
				</div>
				<div class="gameName">
					<%= game.game_name %>
				</div>
				<div class="cat">
					<%= game.description %>
				</div>
				<div class="priceMain">
					<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
				</div>
			</article>
		<% end %>
	<% end %>
</div>

app/views/games/all_top.html.erb
<div class="container">
	<div class="title">
		<h2>برترین ها</h2>
	</div>
	<% all_rates.each do |game| %>

	<%= link_to game, :class => "appLink" do %>
	<article class="app">
		<div class= "coverPhoto">
			<% if game.cover_photo %>
			<%= image_tag game.cover_photo.url %>
			<% end%>
		</div>
		<div class="gameName">
			<%= game.game_name %>
		</div>
		<div class="cat">
			<%= game.description %>
		</div>
		<div class="priceMain">
			<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
		</div>
	</article>
	<% end %>
	<% end %>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<script>
	$(function() {
		if (!flux.browser.supportsTransitions)
			;
		//alert("Flux Slider requires a browser that supports CSS3 transitions");

		window.f = new flux.slider('#slider', {
			pagination : true,
			width : 750,
			height : 300
		});
	});
</script>

<div class="siteName">
	<div class="siteNameTitle">
		بازینــــــــــــــــــــــــــــــــو
	</div>
	<div style="margin-right: 40px;">
	حلقه بین بازی ساز و گیمر موبایل
	</div>
</div>


<%if @isFirstPage%>
<section class="container">
	<div id="slider">
		<% @games.each do |game| %>
		<%= image_tag(game.cover_photo ) %>
		<%end%>
	</div>
</section>

<div class="tozihat">
	اینجا میتونی جدید ترین بازی های موبایل رو دانلود کنی و حالش رو ببری!
	تازه اگه خودت بازی نویس هستی بازی رو بذار اینجا تا بقیه ازش استفاده کنن
</div>
<div class="receptacle">
	<div class="title">
		<h2>برترین ها</h2>
	</div>

	<% top_rates.each do |game| %>
	<%= link_to game, :class => "appLink" do %>
	<article class="app">
		<div class= "coverPhoto">
			<% if game.cover_photo %>
			<%= image_tag game.cover_photo.url %>
			<% end%>
		</div>
		<div class="gameName">
			<%= game.game_name %>
		</div>
		<div class="cat">
			<%= game.description %>
		</div>
		<div class="priceMain">
			<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
		</div>
	</article>
	<% end %>
	<% end %>
	<div class="more">
		<a href="/topgames">بیشتر</a>
	</div>

</div>

<div class="receptacle">

	<div class="title">
		<h2>تازه ها</h2>

	</div>

	<% new_ones.each do |game| %>
	<%= link_to game, :class => "appLink" do %>
	<article class="app">
		<div class= "coverPhoto">
			<% if game.cover_photo %>
			<%= image_tag game.cover_photo.url %>
			<% end%>
		</div>
		<div class="gameName">
			<%= game.game_name %>
		</div>
		<div class="cat">
			<%= game.description %>
		</div>
		<div class="priceMain">
			<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
		</div>
	</article>
	<% end %>
	<% end %>

	<div class="more">
		<a href="/newgames">بیشتر</a>
	</div>

</div>

<div class="receptacle">
	<div class="title">
		<h2>بیشترین دانلود</h2>
	</div>
	<% most_downloads.each do |game| %>
	<%= link_to game, :class => "appLink" do %>
	<article class="app">
		<div class= "coverPhoto">
			<% if game.cover_photo %>
			<%= image_tag game.cover_photo.url %>
			<% end%>
		</div>
		<div class="gameName">
			<%= game.game_name %>
		</div>
		<div class="cat">
			<%= game.description %>
		</div>
		<div class="priceMain">
			<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
		</div>
	</article>
	<% end %>
	<% end %>

	<div class="more">
		<a href="/dowloadedgames">بیشتر</a>
	</div>


	<% else %>

		<div class="receptacle">
			<div class="title">
				<h2>اینارو پیدا کردیم</h2>
			</div>

			<% @games.each do |game| %>
			<%= link_to game, :class => "appLink" do %>
			<article class="app">
				<div class= "coverPhoto">
					<% if game.cover_photo %>
					<%= image_tag game.cover_photo.url %>
					<% end%>
				</div>
				<div class="gameName">
					<%= game.game_name %>
				</div>
				<div class="cat">
					<%= game.description %>
				</div>
				<div class="priceMain">
					<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
				</div>
			</article>
			<% end %>
			<% end %>
			<div class="more">
				<a href="/topgames">بیشتر</a>
			</div>

		</div>

	<% end %>
</div>

app/views/games/new.html.erb
<%= javascript_include_tag "jquery.smartwizard", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "smartwizard-custom", media: "all", "data-turbolinks-track" => true %>

<%= form_for(@game , :html => {:class => "form-horizontal cacade-forms",  :multipart => true }) do |f| %>

<div class="site-holder">
	<div class="box-hol der">
		<!-- .content -->
		<div class="content">

			<!-- Basic Wizard -->
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-dat">
						<div class="panel-body nopadding">
							<!-- Smart Wizard -->
							<div id="wizard" class="swMain">
								<!-- header wizard -->

								<ul>
									<li>
										<a href="#step-1"> <label class="stepNumber">1</label> <span class="stepDesc"> اطلاعات بازی </span> </a>
									</li>
									<li>
										<a href="#step-2"> <label class="stepNumber">2</label> <span class="stepDesc"> توضیحات </span> </a>
									</li>
									<li>
										<a href="#step-3"> <label class="stepNumber">3</label> <span class="stepDesc"> آپلود </span> </a>
									</li>
								</ul>

								<div id="step-1">
									<h2 class="StepTitle">اطلاعات بازی</h2>
									<div class="panel panel-cascade">
										<div class="panel-body">

											<div class="form-group">
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%=f.text_field :game_name, class: "form-control form-cascade-control input-small" %>
												</div>
												<label class="col-lg-2 col-md-2 control-label"> نام بازی </label>

											</div>

											<div class="form-group">
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%=f.text_field :version , class: "form-control form-cascade-control input-small" %>
												</div>
												<label class="col-lg-2 col-md-2 control-label">ورژن </label>
											</div>

											<div class="form-group">
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%= f.select(:platform_id, options_from_collection_for_select(Platform.all, "id", "name"),{}, {:style =>'direction:rtl' , :class => 'form-control form-cascade-control input-small'})%>
												</div>
												<label class="col-lg-2 col-md-2 control-label">پلتفرم</label>
											</div>

											<div class="form-group">
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%= f.select(:genre_id, options_from_collection_for_select(Genre.all, "id", "name"), {}, {:style =>'direction:rtl' ,:class => 'form-control form-cascade-control input-small'} )%>
												</div>
												<label class="col-lg-2 col-md-2 control-label">ژانر</label>
											</div>

											<div class="form-group">
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%=f.text_field :price , class: "form-control form-cascade-control input-small" %>
												</div>
												<label class="col-lg-2 col-md-2 control-label">قیمت </label>
											</div>
										</div>
									</div>
								</div>

								<div id="step-2">
									<h2 class="StepTitle">توضیحات</h2>
									<div class="panel panel-cascade">
										<div class="form-group">
											<div class="col-lg-9 col-md-9 col-lg-offset-1 col-md-offset-1">
												<%=f.text_area :description , class: "form-control form-cascade-control input-small ckeditor" %>
											</div>
											<label class="col-lg-2 col-md-2 control-label">توضیحات </label>
										</div>

								<%= f.fields_for :review do |r| %>
										<div class="form-group">
											<div class="col-lg-9 col-md-9 col-lg-offset-1 col-md-offset-1">
												<%= r.text_area :content ,class: "ckeditor" %>
											</div>
											<label class="col-lg-2 col-md-2 control-label">توضیحات</label>
										</div>
								<% end %>
									</div>
								</div>


								<div id="step-3">
									<h2 class="StepTitle">پایان</h2>
									<div class="panel panel-cascade">
										<div class="panel-heading">
											<div class="form-group">
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%= f.file_field :install_file %>
												</div>
												<label class="col-lg-2 col-md-2 control-label upload-file-title">  فایل بازی</label>
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
													<%= f.file_field :cover_photo %>
												</div>
												<label class="col-lg-2 col-md-2 control-label upload-file-title">  کاور بازی</label>
												<div class="col-lg-6 col-md-6 col-lg-offset-4 col-md-offset-4">
												<%= f.fields_for :video do |v| %>
												  <%= v.file_field :video_file %>
												<% end %>
												</div>
												<label class="col-lg-2 col-md-2 control-label upload-file-title">  ویدیو بازی</label>
											</div>

										</div>
									</div>

								</div>

							</div>
						</div>
					</div>
				</div>

			</div>

		</div>
	</div>
</div>
<% end %>

app/views/games/show.html.erb
<%= stylesheet_link_tag    "comment", media: "all", "data-turbolinks-track" => true %>
<link href="//localhost:3000/video-js.css" rel="stylesheet">
<script src="//localhost:3000/video.js"></script>
<script>videojs.options.flash.swf = "localhost:3000/video-js.swf"</script>

<div class = "col-lg-12" style="margin-top:20px;">
	<div class="gameshow col-lg-l2">
		<div class="detail col-lg-12">
			<div class="download col-lg-9" style="height: 500px;">
				<div class="clo-lg-3"></div>
				<div class="clo-lg-6">
					<%if @game.video%>
					<div class="videoGame">
						<video id="video_id" class="video-js vjs-default-skin vjs-big-play-centered"
						controls preload="auto" width="480" height="320"
						<source src="<%= @game.video.video_file.url%>" />
						</video>
					</div>
					<% end %>
						<div id = "gmn">
						<h2><%= @game.game_name %></h2>
						</div>

						<div id = "devn">
						<h4>برنامه نویس: <%= @game.developer.user.email %></h4>
						</div>

						<div id = "typ">
						<%= link_to @game.genre.name, games_path(:genre_id => @game.genre.id)%>
					</div>

					<div id = "dlbt">
						<div class="btn-group">
							<button type="button" class="btn btn-success col-log-4" id = "wishlist">
								add to wish list
							</button>
							<%= link_to "دانلود", download_game_path, method: :get, class:"btn btn-success clo-lg-4"%>
						</div>
					</div>

					<div class="price">
						قیمت:<%= @game.price %> تومان
					</div>
					<div class="version">
						نسخه:<%= @game.version %>
					</div>
					<div class="line col-lg-8 col-lg-offset-2"></div>

					<div class="col-lg-12">

						<div class="col-lg-4 col-lg-offset-9">
							<div class="follow-widget widget-body">
								<ul>
									<li>
										<%= link_to  like_game_path(@game) ,method: :put  do%>
										<i class="fa fa-thumbs-o-up"></i>
										<%= @game.get_likes.size %>
										<%end%>
									</li>
									<li>
										<%= link_to dislike_game_path(@game), method: :put do %>
										<i class="fa fa-thumbs-o-down"></i>
										<%= @game.get_dislikes.size %>
										<%end%>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-lg-3 ">
				<% if @game.cover_photo %>
				<%= image_tag @game.cover_photo.url , class:"image" %>
				<% end%>
			</div>

		</div>

		<div id ="comm" class="col-lg-12">
			<div class="col-lg-12">
				<div class="row">
					<div class="col-lg-12">
						<div class="widget">
							<div class="widget-header">
								<i class="icon-file"></i>
								<h3>Comments</h3>
							</div>
							<div class="widget-content">

								<div class="timeline-messages">
									<% @game.comments.each do |comment| %>
									<div  class="msg-time-chat">
										<div href="#" class="message-img">
											<%= link_to '#' do %>
											<% if comment.user.profile.avatar %>
											<%= image_tag comment.user.profile.avatar.url , class:"avatar"%>
											<%else%>
											<% image_tag 'empty_avatar.jpg' %>
											<% end%>
											<%end%>
										</div>
										<div class="message-body msg-in">
											<span class="arrow"></span>
											<div class="text">
												<p class="attribution">
													<% if comment.user.profile%>
													<%= comment.user.profile.firstname%>
													<%end%>
													<% if comment.user.profile%>
													<%= comment.user.profile.lastname%>
													<%end%>
													<%= comment.created_at%>
												</p>
												<p style="font-size:25px;">
													<%= comment.body %>
												</p>
											</div>
										</div>
									</div>
									<% end %>
								</div>
								<% if current_user != nil %>
								<%= form_for([@game, @game.comments.build]) do |f|  %>
								<div  class="chat-form">
									<div class="input-cont">
										<%=f.text_area :body, :html=>{ placeholder:"Type a comment here..."}%>
									</div>
									<%=f.submit "send" , class:"btn-cont btn btn-warning"%>
								</div>
								<% end %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="receptacle">
			<div class="title">
				<h2>اینارو پیدا کردیم</h2>
			</div>

			<% @game.genre.games.each do |game| %>
			<%= link_to game, :class => "appLink" do %>
			<article class="app">
				<div class= "coverPhoto">
					<% if game.cover_photo %>
					<%= image_tag game.cover_photo.url %>
					<% end%>
				</div>
				<div class="gameName">
					<%= game.game_name %>
				</div>
				<div class="cat">
					<%= game.description %>
				</div>
				<div class="priceMain">
					<% if game.price!=0 %><%= game.price %> تومان<%else%>رایگان<%end%>
				</div>
			</article>
			<% end %>
			<% end %>
			<div class="more">
				<a href="/topgames">بیشتر</a>
			</div>

		</div>

	</div>
</div>